pipeline {
    agent any

    environment {
        GRADLE_HOME = "${env.WORKSPACE}/CA2/Part1/gradle_basic_demo"
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git url: 'https://github.com/NathaliaTGodoy/devops-23-24-PSM-1231864.git'
            }
        }

        stage('Assemble') {
            steps {
                echo 'Assembling...'
                dir("${GRADLE_HOME}") {
                    sh 'chmod +x gradlew'
                    sh './gradlew assemble'
                }
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
                dir("${GRADLE_HOME}") {
                    sh './gradlew test'
                    junit 'build/test-results/test/*.xml'
                }
            }
        }

        stage('Archive') {
            steps {
                echo 'Archiving...'
                dir("${GRADLE_HOME}") {
                    archiveArtifacts artifacts: 'build/libs/*.jar', allowEmptyArchive: true
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
